### ISSUE TITLE
The sidebar_behavior is not correct when accessed from domain redirect

### ISSUE THREAD

**Issue by fuji246** [LouisBarranqueiro/hexo-theme-tranquilpeak#265] opened 2016-05-31 04:52 UTC
### Configuration
- **Operating system with version** : 
- **Node version** : 
- **Hexo version** : 
- **Hexo-cli version** : 
- **Tranquilpeak version** : 1.7.1

### Actual behavior

Using phone device, open http://yuzhi.info, will show the sidebar, but if using http://oliviafu.github.io, the layout is correct.

Using tinyurl doesn't have this problem

### Expected behavior

Same behavior after domain redirect

**Comment by LouisBarranqueiro** [comment] 2016-05-31 18:12
hey @fuji246, which version doesn't have this problem?

**Comment by fuji246** [comment] 2016-05-31 19:39
oh, sorry, my mistake, i was not using domain redirect for the old version.

2016-05-31 11:12 GMT-07:00 Louis Barranqueiro <notifications@github.com>:

**Comment by LouisBarranqueiro** [comment] 2016-05-31 19:41
so is it working?

**Comment by fuji246** [comment] 2016-05-31 19:55
I don't have other domain name to do that test, however i tried tinyurl,
which use redirect i think.

tinyurl works for both.

So i don't think old version works.

I don't know how the sidebar_behavoir works under-the-neath, seems it's
using Sass lib to determine the screen size?

2016-05-31 12:41 GMT-07:00 Louis Barranqueiro <notifications@github.com>:

**Comment by LouisBarranqueiro** [comment] 2016-05-31 19:58
since it's working on a domain and not on another one, I think that it's not related to the theme. sidebar_behavior is generated during the `hexo generate` step. it's static. and the css do the rest

**Comment by LouisBarranqueiro** [comment] 2016-07-02 20:44
Hey @fuji246, Is it working?

**Comment by LouisBarranqueiro** [comment] 2016-07-19 18:28
Can we close it @fuji246 ?

**Comment by fuji246** [comment] 2016-07-20 06:06
Hey Louis, you can use the phone to access http://yuzhi.info and
http://oliviafu.github.io.

The layout is different.

2016-07-19 11:28 GMT-07:00 Louis Barranqueiro <notifications@github.com>:

**Comment by LouisBarranqueiro** [comment] 2016-08-24 14:57
I'm sorry man but I don't have enough information to help you.

> oh, sorry, my mistake, i was not using domain redirect for the old version.

Why did you said that, if it's still not working?

**Comment by robinWongM** [comment] 2016-08-26 05:51
I visited the website using my phone. ( Android 5.1.1 & QQBrowser v6.8 )
Here is the result:

yuzhi.info
![yuzhi.info](https://cloud.githubusercontent.com/assets/2606137/17995126/a77972fa-6b91-11e6-880c-1017064c2d89.png)

oliviafu.github.io
![github.io](https://cloud.githubusercontent.com/assets/2606137/17995146/cb507ca0-6b91-11e6-83b3-425239f4e573.png)

It looks like that scaling resulted in the problem.
Then I checked the source of yuzhi.info:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">
<html>

<head>
  <title>yuzhi.info</title>
  
</head>
<frameset rows="100%,*" border="0">
  <frame src="http://oliviafu.github.io/" frameborder="0" />
  <frame frameborder="0" noresize />
</frameset>

<!-- pageok -->
<!-- 03 -->
<!-- -->
</html>
```
It uses frame to embed the website and doesn't set `<meta name="viewport" content="width=device-width, initial-scale=1.0">`. So the problem isn't related to the theme. 
I suggest adding `<meta name="viewport" content="width=device-width, initial-scale=1.0">` to the source code of webpage. This should solve the problem.
-------
I have something(not related to the theme) to tell @fuji246 since we are both Chinese:
GitHub Pages 要绑定域名的话可以在使用 cname 绑定的，不需要大费周折加个 frame 来内嵌远程网站。正如你所见，用手机访问 yuzhi.info 会缩放（从而导致侧边栏出现），这是因为 yuzhi.info 的网页源代码里没有设定 viewport，如果直接绑定域名的话就不会出现这个问题。

**Closed** 2017-01-13 22:28 UTC
