### ISSUE TITLE
Uncaught ReferenceError if algolia is not configured

### ISSUE THREAD

**Issue by kakawait** [LouisBarranqueiro/hexo-theme-tranquilpeak#302] opened 2016-07-17 09:36 UTC
### Configuration

 - **Operating system with version** :  Mac OSX 10.11.5 with Chrome 51
 - **Node version** : 6.3.0
 - **Hexo version** : 3.2.0
 - **Hexo-cli version** : 1.0.2
 - **Tranquilpeak version** : 1.9.0
 

### Actual behavior

```
script-taaobz4ueybn54ikf9gtu3wlm8tpgzjkwfknygrtitquljbwokv26p56moto.min.js:4 Uncaught ReferenceError: algoliaIndex is not defined
```
if _Algolia_ is not configured inside `_config.yml`

### Expected behavior

No JS error if we do not configure _Algolia_

### Steps to reproduce the behavior

1. Remove/comment _Algolia_ conf inside `_config.yml`

**Comment by LouisBarranqueiro** [comment] 2016-07-17 10:19
This one is a duplicate of https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/296

**Closed** 2016-07-19 18:34 UTC
Labels: duplicate
